# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

################################################################################
# Use node image for base image for all stages.
FROM node:22-alpine

# Set working directory for all build stages.
WORKDIR /client

COPY package*.json ./

# Download development dependencies before building.
RUN npm ci

# Copy the rest of the source files into the image.
COPY . .

# Expose the port that the application listens on.
EXPOSE 5173

# Run the application.
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
